### ISSUE TITLE
`%` over `@define-placeholder`

### ISSUE THREAD

**Issue by VinSpee** [davidtheclark/postcss-simple-extend#3]
Any particular reason you used `@define-placeholder` over `%` (which is in [the proposal](https://tabatkins.github.io/specs/css-extend-rule/#placeholder-selector))?

**Comment by davidtheclark** [comment]
Yeah: the reason is that I wanted to use an existing flexible language construct, the at-rule, instead of trying to introduce a new one for just this purpose.

I'm not sure how far along that proposal is, how plausible it is that it will continue and eventually be adopted. Unless it's important to you or others I'd hesitate to try to introduce `%` at least until that is more likely to become a reality. Is it important?

I'll leave this open to see if other people have opinions on the issue.

**Comment by VinSpee** [comment]
Not really important to me, and I suspected that was the reason. I was just
curious! I agree the spec syntax is likely to change before then so it's
not really a concern of mine at this point - I just try to keep things as
"future-friendly" as possible. I have no real qualms with the current
implementation.

**Comment by mattecapu** [comment]
I'd make that cleare in the README because in the first lines it's stated

> The functionality should mirror Sass's @extend with % placeholders

Thus maybe later on, when explaining the syntax, it could be useful to explicitly state that `%` it's not supported

**Comment by davidtheclark** [comment]
@mattecapu : Done at https://github.com/davidtheclark/postcss-simple-extend/blob/master/README.md#usage

**Comment by mattecapu** [comment]
@davidtheclark great!
